// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyJParRRd3v3iIh6pl6BziOOzWxFlH8cw',
    appId: '1:819563344900:web:23c67dab6aac9f079f7151',
    messagingSenderId: '819563344900',
    projectId: 'mytodolist-1565f',
    authDomain: 'mytodolist-1565f.firebaseapp.com',
    storageBucket: 'mytodolist-1565f.firebasestorage.app',
    measurementId: 'G-W3CMRVM3M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDVjRfRxOO80zkh453u_6dkRNjN0AMq7c',
    appId: '1:819563344900:android:e189f2fa671821449f7151',
    messagingSenderId: '819563344900',
    projectId: 'mytodolist-1565f',
    storageBucket: 'mytodolist-1565f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCgfOAcPTizapKhJXQBh2zTsmqObPewI',
    appId: '1:819563344900:ios:a61f3ea59e9d252a9f7151',
    messagingSenderId: '819563344900',
    projectId: 'mytodolist-1565f',
    storageBucket: 'mytodolist-1565f.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVCgfOAcPTizapKhJXQBh2zTsmqObPewI',
    appId: '1:819563344900:ios:a61f3ea59e9d252a9f7151',
    messagingSenderId: '819563344900',
    projectId: 'mytodolist-1565f',
    storageBucket: 'mytodolist-1565f.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyJParRRd3v3iIh6pl6BziOOzWxFlH8cw',
    appId: '1:819563344900:web:53922506ac94a7dc9f7151',
    messagingSenderId: '819563344900',
    projectId: 'mytodolist-1565f',
    authDomain: 'mytodolist-1565f.firebaseapp.com',
    storageBucket: 'mytodolist-1565f.firebasestorage.app',
    measurementId: 'G-6HEKDPLSGR',
  );
}
